### ISSUE TITLE
Couldn't compile latex documentation

### ISSUE THREAD

**Issue by JohnGriffiths** [the-virtual-brain/tvb-documentation#4]
Error:

>-documentation$ make latex
>sphinx-build -b latex -d _build/doctrees   . _build/latex
>Running Sphinx v1.2.2

>Exception occurred:
>  File "conf.py", line 19, in <module>
>    from tvb.basic.profile import TvbProfile
>ImportError: No module named tvb.basic.profile
>The full traceback has been saved in /tmp/sphinx-err-Bba3Bv.log, if you want to report the issue to the developers.
>Please also report this if it was a user error, so that a better error message can be provided next time.
>A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [latex] Error 1

Contents of the .log file in /tmp mentioned in above text:

>(_tvb)jgriffiths@cpac:/alexandra/mcintosh_lab/john/Code/libraries_of_mine/github/tvb-documentation$ cat /tmp/sphinx-err-Bba3Bv.log
> Sphinx version: 1.2.2
> Python version: 2.7.6
> Docutils version: 0.11 release
> Jinja2 version: 2.7.2
> Loaded extensions:
>Traceback (most recent call last):
> File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 253, in main
>   warningiserror, tags, verbosity, parallel)
>  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 107, in __init__
>    confoverrides or {}, self.tags)
>  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 229, in __init__
>    execfile_(filename, config)
>  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 105, in execfile_
>    exec code in _globals
>  File "conf.py", line 19, in <module>
>    from tvb.basic.profile import TvbProfile
>ImportError: No module named tvb.basic.profile

**Comment by maedoc** [comment]
> from tvb.basic.profile import TvbProfile
> ImportError: No module named tvb.basic.profile

This line says it all; you need TVB's modules in your Python path, the easiest being to `export PYTHONPATH=...` before issuing `make latex`.

**Comment by JohnGriffiths** [comment]
I am running `make latex` from within a tvb virtualenv, so thought that the necessary modules were already on the python path. 

In any case, running `export PYTHONPATH=..` a few times before `make latex` does seem to have fixed it though; thanks.
