### ISSUE TITLE
Tutorials page

### ISSUE THREAD

**Issue by JohnGriffiths** [the-virtual-brain/tvb-documentation#5]
Since we decided to use the tvb-documentation tutorials for Node#3, I think the [tutorials page](http://docs.thevirtualbrain.org/tutorials/Tutorials.html) needs a little tidying, as we will be pointing workshop attendees to this webpage for the hands on sessions (in addition to giving them PDFs compiled from these pages). 

A few points:

1. The content of the 'Building Your Own Brain Network Model' tutorial corresponds to the 
The Node#2 handout called 'Brain Network Models At Rest', and will be given at Node#3 in a session called 'Hands-on: Modeling brain networks at rest'. Could this tutorial also be renamed to something like 'Brain Network Models At Rest' for consistency?

2. The non-existent  'Resting State Networks' tutorial listing compounds this ambiguity. Can this be removed?

3. Can the empty scripting tutorial listings be removed or links added?

**Comment by timpx** [comment]
Hi John, the 'Building Your Own Brain Network Model' tutorial corresponds to Node #1 handout 'Building Your Own Brain Network Model' and should follow closely the corresponding GUI tutorial. It's about getting the basic steps to perform region-based and surface-based simulations. The  'Resting State Networks' tutorial is about a working example of simulating the RSNs, and is still to be done.

**Comment by JohnGriffiths** [comment]
Ok thanks. 

So how do people feel about 

a) removing the RSNs tutorial link until the that tutorial is ready, and 

b) renaming 'Building Your Own Brain Network Model' to 'Brain Network Models At Rest', so as to match the workshop and previous handout terminology. Perhaps when the RSNs tutorial is available it would make sense to switch the name back again. 

?

**Comment by maedoc** [comment]
I'm fine with both, though I will have the RSNs tutorial done end of next week.

**Comment by liadomide** [comment]
Will this be solved after this task becomes done: http://req.thevirtualbrain.org/browse/TVB-1986 ?

**Comment by maedoc** [comment]
Yes, it's still in progress.

**Comment by liadomide** [comment]
As it doesn't hold extra requirements which are not already in Jira, 
I suggest to close this task, in the effort to go towards having a single task management tool.

**Comment by maedoc** [comment]
closed, with corresponding issues in JIRA:

- http://req.thevirtualbrain.org/browse/TVB-1986
- http://req.thevirtualbrain.org/browse/TVB-1903
