### ISSUE TITLE
Tutorials pdf

### ISSUE THREAD

**Issue by JohnGriffiths** [the-virtual-brain/tvb-documentation#6]
Is there a makefile somewhere for creating a pdf / pdfs from tvb-documentation/tutorials?

**Comment by maedoc** [comment]
No but if you've got `pandoc` and `pdflatex` installed, something like

```
ipython nbconvert tuto.ipynb --to pdf
```

will do the trick. pull request welcome ;)

**Comment by JohnGriffiths** [comment]
Well the reason for asking is that we (e-mail conversation with Lia, Tim, Paula, Tanya; apologies you weren't in that) agreed to use the HTML tutorials for Node #3, but also to provide PDFs of them so internet access isn't required.  

I can look into this if you like.

**Comment by JohnGriffiths** [comment]
Investigating further it looks like adding the correct changes to `tvb-documentation/index.rst` and `tvb-documentation/conf.py` should produce a PDFs for the tutorials. I can't figure out what changes need to be made though; tried a few and keep getting the main `UserGuide.pdf` only.

**Comment by maedoc** [comment]
http://stackoverflow.com/questions/15879276/any-way-to-generate-multiple-different-pdfs-from-single-sphinx-configuration

?

**Comment by JohnGriffiths** [comment]
Yes indeed; adding the tuple

`('tutorials/Tutorials', 'Tutorials.tex', 'Web Tutorials', author_names, 'manual')`

to `conf.py`

Does now produce a tutorials PDF. Needs a good deal more custom formatting though I think.
