### ISSUE TITLE
Visualizers: Translating the brain by right mouse button

### ISSUE THREAD

**Issue by danielberlin** [the-virtual-brain/tvb-documentation#8]
On https://github.com/the-virtual-brain/tvb-documentation/blob/master/manuals/UserGuide/UserGuide-UI_Simulator-Visualizers.rst it says: "the right button translates the brain." and "Pressing the shift key and the left button has the same effect as the right button."

However, on Macs the right button functionality is achieved by pressing CTRL+left button and not Shift+left button (I wonder if it is intentional not to keep on these standards?). I also cannot reproduce the functionality "translating the brain" by either of the combinations. Help appreciated.

**Comment by maedoc** [comment]
@liadomide @timpx mac users, could you take a look?

**Comment by liadomide** [comment]
I was just testing these:
- on my machine (Mac 10.10.5, Chrome || FF  latest versions) it works in the manner written in the documentation:  CTRL + left mouse changes the rotation center to in the model space.
- as for the "standard" CTRL + left mouse == Right mouse. I can confirm: in most mac applications, this is right. Although, I was not aware it is common, and I didn't really use it before.
